# Jekyll Resume Theme

# Site settings
title: Jonghyeon-lee Resume
email: hugethic@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
#baseurl: "http://mattcouchman.co.uk/jekyll-resume/"
baseurl: "http://jonghyeon-lee.github.io/"
#url: "http://mattcouchman.co.uk/jekyll-resume/"
url: "http://jonghyeon-lee.github.io/"
name: Jonghyeon Lee
job: back end engineer
location: Seoul, Korea
languages: java, python-flask, node.js
github_username:  jonghyeon-lee
email_address: hugethic@gmail.com

# Build settings
markdown: kramdown
